### PR TITLE
Weekly Update: 9/5 - 9/9

### PR DESCRIPTION
**Pull request by cafreeman**
Everyone fill out your sections!

### CODE REVIEW

**Comment by Robdel12** [comment]
👀

**Comment by ssriera** [comment]
Rob stop checking GH & go get a tan by the pool or something >.>

**Comment by cowboyd** [comment]
So I imagined that I was somebody from outside our company trying to read this email, which is I believe, what Rob's eventual plan is, and I couldn't really make sense of it. I tried to add some explatanory text at the beginning to introduce each project and explain _why_

I think in the future when we write our individual updates, we need to imagine this audience and that we're talking not just to each other, but also to the larger world.

**Comment by cowboyd** [comment]
5 minute warning!

**Pull request merged**
